/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 0.99.3. DO NOT MODIFY.
*/
module test
    ( // Inputs
      input  clock // clock
    , input  reset // asynchronous reset: active high
    , input [7:0] x 
    , input [7:0] y 

      // Outputs
    , output wire [7:0] out 
    );


  assign out = x * y;
endmodule

